# Generated by Django 5.0 on 2024-08-28 20:54

from django.db import migrations, models


def _update_licence(apps, *_):
    Member = apps.get_model("members", "Member")
    for member in Member.objects.filter(ffd_license__gt=0).all():
        member.ffd_license += 5
        member.save()


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="ffd_license",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Aucune"),
                    (24, "Licence A Loisir"),
                    (26, "Licence B Compétiteur"),
                    (43, "Licence C Compétiteur national"),
                    (55, "Licence D Compétiteur international"),
                ],
                default=0,
            ),
        ),
        migrations.RunPython(_update_licence),
    ]
