# Generated by Django 4.2.13 on 2024-07-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ffd_license',
            field=models.PositiveIntegerField(choices=[(0, 'Aucune'), (19, 'Licence A Loisir'), (21, 'Licence B Compétiteur'), (38, 'Licence C Compétiteur national'), (50, 'Licence D Compétiteur international')], default=0),
        ),
    ]
