# Generated by Django 5.0 on 2026-01-25 10:44
import re

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _create_default_settings(apps, *_):
    GeneralSettings = apps.get_model("members", "GeneralSettings")
    GeneralSettings().save()


def _update_addresses(apps, *_):
    Member = apps.get_model("members", "Member")
    pattern = r"([\w\s]+)\s(\d{5})\s(\w+)"
    for member in Member.objects.all():
        found = re.findall(pattern, member.address)
        if found:
            new_address, postal_code, city = found[0]
            member.address = new_address
            member.postal_code = postal_code
            member.city = city
            member.save()


class Migration(migrations.Migration):
    replaces = [
        ("members", "0002_remove_sportpass_amount_season_pass_sport_amount_and_more"),
        ("members", "0003_generalsettings"),
        ("members", "0004_season_ffd_a_amount_season_ffd_b_amount_and_more"),
        ("members", "0005_member_city_member_postal_code"),
        ("members", "0006_course_capacity_member_waiting_courses"),
        ("members", "0007_course_stripe_price_amount_course_stripe_price_id_and_more"),
        ("members", "0008_season_ffd_a_stripe_price_id_and_more"),
        ("members", "0009_season_pre_signup_end_season_pre_signup_start"),
        ("members", "0010_season_signup_end_season_signup_start"),
        ("members", "0011_remove_course_stripe_price_id_and_more"),
        ("members", "0012_alter_member_user"),
        ("members", "0013_generalsettings_display_signup_info_and_more"),
        ("members", "0014_alter_season_year"),
        ("members", "0015_generalsettings_signup_payment_delta_days"),
        ("members", "0016_waitinglist"),
    ]

    dependencies = [
        ("members", "0001_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sportpass",
            name="amount",
        ),
        migrations.AddField(
            model_name="season",
            name="pass_sport_amount",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="member",
            name="sport_pass",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.sportpass",
            ),
        ),
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_signup", models.BooleanField(default=True)),
                ("allow_new_member", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            code=_create_default_settings,
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_a_amount",
            field=models.PositiveIntegerField(
                default=24, verbose_name="Licence A Loisir price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_b_amount",
            field=models.PositiveIntegerField(
                default=26, verbose_name="Licence B Compétiteur price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_c_amount",
            field=models.PositiveIntegerField(
                default=43, verbose_name="Licence C Compétiteur national price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_d_amount",
            field=models.PositiveIntegerField(
                default=55, verbose_name="Licence D Compétiteur international price"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="ffd_license",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(default="Villemur sur Tarn", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="postal_code",
            field=models.CharField(default="31340", max_length=5),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=_update_addresses,
        ),
        migrations.AddField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="member",
            name="waiting_courses",
            field=models.ManyToManyField(
                related_name="members_waiting", to="members.course"
            ),
        ),
        migrations.CreateModel(
            name="CBPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cb_payment",
                        to="members.payment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="season",
            name="pre_signup_end",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="pre_signup_start",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="signup_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="signup_start",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="pre_signup_payment_delta_days",
            field=models.PositiveBigIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="season",
            name="year",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[django.core.validators.RegexValidator("\\d{4}-\\d{4}")],
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="signup_payment_delta_days",
            field=models.PositiveBigIntegerField(default=7),
        ),
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signup_date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.course"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
            ],
            options={
                "unique_together": {("course", "member")},
            },
        ),
    ]
