# Generated by Django 5.0 on 2024-08-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
