# Generated by Django 4.2.13 on 2024-06-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'season', 'weekday', 'start_hour')},
        ),
    ]
