# Generated by Django 5.0 on 2025-03-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sportpass",
            name="amount",
        ),
        migrations.AddField(
            model_name="season",
            name="pass_sport_amount",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="member",
            name="sport_pass",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.sportpass",
            ),
        ),
    ]
