# Generated by Django 5.0 on 2024-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='active_courses',
            field=models.ManyToManyField(related_name='members', to='members.course'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cancelled_courses',
            field=models.ManyToManyField(related_name='members_cancelled', to='members.course'),
        ),
        migrations.AlterField(
            model_name='member',
            name='contacts',
            field=models.ManyToManyField(to='members.contact'),
        ),
    ]
