# Generated by Django 5.0 on 2024-08-04 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_active_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='special_discount',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
