# Generated by Django 4.2.13 on 2024-06-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
