# Generated by Django 5.0 on 2025-03-14 14:21

from django.db import migrations, models


def _create_default_settings(apps, *_):
    GeneralSettings = apps.get_model("members", "GeneralSettings")
    GeneralSettings().save()


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_remove_sportpass_amount_season_pass_sport_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_signup", models.BooleanField(default=True)),
                ("allow_new_member", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(_create_default_settings),
    ]
