# Generated by Django 5.0 on 2026-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="adhesion_fee",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
