# Generated by Django 5.0 on 2026-04-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_season_adhesion_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="month",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Janvier"),
                    (2, "Février"),
                    (3, "Mars"),
                    (4, "Avril"),
                    (5, "Mai"),
                    (6, "Juin"),
                    (7, "Juillet"),
                    (8, "Aout"),
                    (9, "Septembre"),
                    (10, "Octobre"),
                    (11, "Novembre"),
                    (12, "Décembre"),
                    (100, "Caution"),
                ]
            ),
        ),
    ]
