# Generated by Django 4.2.13 on 2024-06-18 11:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0003_member_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('first_name', 'last_name', 'user')},
        ),
    ]
