# Generated by Django 4.2.13 on 2024-07-21 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='courses',
            new_name='active_courses',
        ),
    ]
