# Generated by Django 4.2.13 on 2024-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_season_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='weekday',
            field=models.PositiveIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')]),
        ),
    ]
