# Generated by Django 5.0 on 2025-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_generalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="ffd_a_amount",
            field=models.PositiveIntegerField(
                default=24, verbose_name="Licence A Loisir price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_b_amount",
            field=models.PositiveIntegerField(
                default=26, verbose_name="Licence B Compétiteur price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_c_amount",
            field=models.PositiveIntegerField(
                default=43, verbose_name="Licence C Compétiteur national price"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_d_amount",
            field=models.PositiveIntegerField(
                default=55, verbose_name="Licence D Compétiteur international price"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="ffd_license",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
