# Generated by Django 4.2.13 on 2024-06-20 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0004_alter_member_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.season'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('first_name', 'last_name', 'user', 'season')},
        ),
    ]
