# Generated by Django 5.0 on 2026-04-14 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_alter_check_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="number",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.RegexValidator("\\d{1,10}")],
            ),
        ),
    ]
