# Generated by Django 5.0 on 2025-03-23 20:04
import re

from django.db import migrations, models


def _update_addresses(apps, *_):
    Member = apps.get_model("members", "Member")
    pattern = r"([\w\s]+)\s(\d{5})\s(\w+)"
    for member in Member.objects.all():
        found = re.findall(pattern, member.address)
        if found:
            new_address, postal_code, city = found[0]
            member.address = new_address
            member.postal_code = postal_code
            member.city = city
            member.save()


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_season_ffd_a_amount_season_ffd_b_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(default="Villemur sur Tarn", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="postal_code",
            field=models.CharField(default="31340", max_length=5),
            preserve_default=False,
        ),
        migrations.RunPython(_update_addresses),
    ]
