# Generated by Django 4.2.13 on 2024-06-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_course_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
