# Generated by Django 4.2.13 on 2024-07-21 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_courses_member_active_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cancel_refund',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='member',
            name='cancelled_courses',
            field=models.ManyToManyField(related_name='members', to='members.course'),
        ),
        migrations.AlterField(
            model_name='member',
            name='contacts',
            field=models.ManyToManyField(related_name='members_cancelled', to='members.contact'),
        ),
    ]
