# Generated by Django 4.2.13 on 2024-06-20 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_unique_together_member_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='discount_limit',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='season',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
