# Generated by Django 5.0 on 2025-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_member_city_member_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="capacity",
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name="member",
            name="waiting_courses",
            field=models.ManyToManyField(
                related_name="members_waiting", to="members.course"
            ),
        ),
    ]
