# Generated by Django 5.0 on 2026-04-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_check_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="max_year",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="min_year",
            field=models.PositiveIntegerField(default=1900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="next_courses",
            field=models.ManyToManyField(
                related_name="members_next", to="members.course"
            ),
        ),
    ]
