# Generated by Django 4.2.13 on 2024-06-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_season_discount_limit_season_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='season',
        ),
        migrations.AlterField(
            model_name='documents',
            name='authorise_emergency',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='medical_document',
            field=models.CharField(choices=[('Manquant', 'Manquant'), ('Certificat', 'Certificat'), ('Attestation', 'Attestation')], default='Manquant', max_length=11),
        ),
    ]
