# Generated by Django 5.0 on 2026-05-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_course_from_year_course_to_year_member_next_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="from_pk",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
