# Generated by Django 5.0 on 2025-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_course_stripe_price_amount_course_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="ffd_a_stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_b_stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_c_stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_d_stripe_price_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="season",
            name="ffd_stripe_product_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
