# Generated by Django 5.0 on 2026-05-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_member_from_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="teacher",
            name="skills",
            field=models.ManyToManyField(related_name="teachers", to="members.skill"),
        ),
    ]
