# Generated by Django 4.2.13 on 2024-06-22 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_payment_paid_payment_cash_payment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_payment', to='members.payment'),
        ),
        migrations.AlterField(
            model_name='sportcoupon',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sport_coupon', to='members.payment'),
        ),
        migrations.AlterField(
            model_name='sportpass',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_pass', to='members.payment'),
        ),
    ]
