# Generated by Django 5.0 on 2025-05-18 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_season_ffd_a_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="pre_signup_end",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="pre_signup_start",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
