# Generated by Django 5.0 on 2026-05-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0008_skill_teacher_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="skill",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.skill",
            ),
        ),
    ]
