# Generated by Django 5.0 on 2026-08-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_course_skill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="pre_signup_end",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="season",
            name="pre_signup_start",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="season",
            name="signup_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="signup_start",
            field=models.DateTimeField(null=True),
        ),
    ]
