# Generated by Django 4.2.13 on 2024-06-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_otherpayment_payment_alter_sportcoupon_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_payment', to='members.payment'),
        ),
    ]
