# Generated by Django 5.0 on 2025-05-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_season_pre_signup_end_season_pre_signup_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="signup_end",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="signup_start",
            field=models.DateField(null=True),
        ),
    ]
