# Generated by Django 5.0 on 2026-09-01 11:26

from datetime import timedelta
import django.utils.timezone
from django.db import migrations, models


def _update_signup_dates(apps, *_):
    GeneralSettings = apps.get_model("members", "GeneralSettings")
    Season = apps.get_model("members", "Season")
    general_settings = GeneralSettings.objects.first()
    for season in Season.objects.all():
        season.pre_signup_end_payment = season.pre_signup_end + timedelta(
            days=general_settings.pre_signup_payment_delta_days
        )
        if season.signup_end is not None:
            season.signup_end_payment = season.signup_end + timedelta(
                days=general_settings.signup_payment_delta_days
            )
        season.save()


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_alter_season_pre_signup_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="pre_signup_end_payment",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="season",
            name="signup_end_payment",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(_update_signup_dates),
        migrations.RemoveField(
            model_name="generalsettings",
            name="pre_signup_payment_delta_days",
        ),
        migrations.RemoveField(
            model_name="generalsettings",
            name="signup_payment_delta_days",
        ),
    ]
