# Generated by Django 4.2.13 on 2024-06-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_check_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
    ]
