# Generated by Django 5.0 on 2025-05-25 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0010_season_signup_end_season_signup_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="season",
            name="ffd_a_stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="season",
            name="ffd_b_stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="season",
            name="ffd_c_stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="season",
            name="ffd_d_stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="season",
            name="ffd_stripe_product_id",
        ),
    ]
