# Generated by Django 4.2.13 on 2024-06-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_member_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportpass',
            name='payment',
        ),
        migrations.AddField(
            model_name='member',
            name='sport_pass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.sportpass'),
        ),
    ]
