# Generated by Django 5.0 on 2025-06-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_alter_member_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="pre_signup_payment_delta_days",
            field=models.PositiveBigIntegerField(default=7),
        ),
    ]
