# Generated by Django 4.2.13 on 2024-06-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_sportpass_payment_member_sport_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherpayment',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='other_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.otherpayment'),
        ),
    ]
