# Generated by Django 5.0 on 2025-06-15 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0013_generalsettings_display_signup_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="year",
            field=models.CharField(
                max_length=9,
                unique=True,
                validators=[django.core.validators.RegexValidator("\\d{4}-\\d{4}")],
            ),
        ),
    ]
