# Generated by Django 4.2.13 on 2024-07-02 03:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_otherpayment_payment_payment_other_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=150, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\d{10}')])),
                ('contact_type', models.CharField(choices=[('Responsable légal', 'Responsable légal'), ("Contact d'urgence", "Contact d'urgence")], max_length=17)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.season')),
            ],
            options={
                'unique_together': {('first_name', 'last_name', 'season')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='contacts',
            field=models.ManyToManyField(to='members.contact'),
        ),
    ]
