# Generated by Django 4.2.13 on 2024-07-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_contact_member_contacts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='season',
        ),
    ]
