# Generated by Django 4.2.13 on 2024-07-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_contact_unique_together_remove_contact_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'last_name', 'contact_type')},
        ),
    ]
