# Generated by Django 4.2.13 on 2024-07-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
