# Generated by Django 4.2.13 on 2024-07-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_contact_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('RESPONSIBLE', 'Responsable légal'), ('EMERGENCY', "Contact d'urgence")], max_length=17),
        ),
    ]
