# Generated by Django 4.2.13 on 2024-07-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('responsible', 'Responsable légal'), ('emergency', "Contact d'urgence")], max_length=17),
        ),
    ]
