# Generated by Django 4.2.13 on 2024-07-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='medical_document',
            field=models.CharField(choices=[('Manquant', 'Manquant'), ('Certificat', 'Certificat'), ('Attestation', 'Attestation')], max_length=11),
        ),
    ]
