# Generated by Django 4.2.13 on 2024-07-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_documents_medical_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='medical_document',
            field=models.CharField(choices=[('Manquant', 'Manquant'), ('Certificat', 'Certificat'), ('Attestation', 'Attestation')], default='Manquant', max_length=11),
        ),
    ]
