# Generated by Django 4.2.13 on 2024-07-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_alter_documents_medical_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='documents',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.documents'),
        ),
    ]
