# Generated by Django 4.2.13 on 2024-06-13 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def _create_superuser(apps, *_):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    superuser = User.objects.create_superuser(
        username=settings.SUPERUSER,
        email=settings.SUPERUSER_EMAIL,
        password=settings.DEFAULT_PWD,
    )
    Profile(
        user=superuser,
        address=settings.SUPERUSER_ADDRESS,
        phone=settings.SUPERUSER_PHONE,
    ).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\d{10}')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_hash', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(_create_superuser),
    ]
