# Generated by Django 5.0 on 2025-03-09 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _create_superuser(apps, *_):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("accounts", "Profile")
    superuser = User.objects.create_superuser(
        username=settings.SUPERUSER_EMAIL,
        email=settings.SUPERUSER_EMAIL,
        password=settings.SUPERUSER_PWD,
    )
    Profile(
        user=superuser,
        address=settings.SUPERUSER_ADDRESS,
        phone=settings.SUPERUSER_PHONE,
    ).save()


def _create_teacher_group(apps, *_):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=settings.TEACHER_GROUP_NAME)


class Migration(migrations.Migration):
    replaces = [("accounts", "0001_initial"), ("accounts", "0002_auto_20241006_1148")]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                (
                    "phone",
                    models.CharField(
                        max_length=10,
                        validators=[django.core.validators.RegexValidator("\\d{10}")],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResetPassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_hash", models.CharField(max_length=128)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(_create_superuser),
        migrations.RunPython(_create_teacher_group),
    ]
