# Generated by Django 5.0 on 2024-10-06 09:48

from django.conf import settings
from django.db import migrations


def _create_teacher_group(apps, *_):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name=settings.TEACHER_GROUP_NAME)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(_create_teacher_group),
    ]
