# Generated by Django 5.0 on 2025-03-23 20:04
import re

from django.db import migrations, models


def _update_addresses(apps, *_):
    Profile = apps.get_model("accounts", "Profile")
    pattern = r"([\w\s]+)\s(\d{5})\s(\w+)"
    for profile in Profile.objects.all():
        found = re.findall(pattern, profile.address)
        if found:
            new_address, postal_code, city = found[0]
            profile.address = new_address
            profile.postal_code = postal_code
            profile.city = city
            profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(default="Villemur sur Tarn", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(default="31340", max_length=5),
            preserve_default=False,
        ),
        migrations.RunPython(_update_addresses),
    ]
